- hosts: workstation
  gather_facts: false
  tasks:
  - name: OpenStack servers
    os_server_info:
     cloud: openstack
     server: 'frontend'
    register: openstack_info
    tags:
      - osp.smoke
  - debug :
      msg: " {{  openstack_info }} "
