---
# Initial, common, system setup steps

- name: enable sudo without tty for some ansible commands
  replace:
    path: /etc/sudoers
    regexp: '^Defaults\s*requiretty'
    replace: 'Defaults  !requiretty'
    backup: yes

- name: enable repos

  yum_repository:
    name: rhel-8-for-x86_64-appstream-rpms
    description: EPEL YUM repo
    file: internal
    baseurl:http://192.0.2.253/repos/rhel-8-for-x86_64-appstream-rpms
    gpgcheck: no
  yum_repository:
    name: rhel-8-for-x86_64-baseos-rpms
    description: EPEL YUM repo
    file: internal
    baseurl:http://192.0.2.253/repos/rhel-8-for-x86_64-baseos-rpms
    gpgcheck: no
  yum_repository:
    name: rhel-8-for-x86_64-highavailability-rpms
    description: EPEL YUM repo
    file: internal
    baseurl:http://192.0.2.253/repos/rhel-8-for-x86_64-highavailability-rpms
    gpgcheck: no
  yum_repository:
    name: openstack-16-for-rhel-8-x86_64-rpms
    description: EPEL YUM repo
    file: internal
    baseurl:http://192.0.2.253/repos/openstack-16-for-rhel-8-x86_64-rpms
    gpgcheck: no
  yum_repository:
    name: fast-datapath-for-rhel-8-x86_64-rpms
    description: EPEL YUM repo
    file: internal
    baseurl:http://192.0.2.253/repos/fast-datapath-for-rhel-8-x86_64-rpms
    gpgcheck: no
  yum_repository:
    name: ansible-2.8-for-rhel-8-x86_64-rpm
    description: EPEL YUM repo
    file: internal
    baseurl:http://192.0.2.253/repos/ansible-2.8-for-rhel-8-x86_64-rpms
    gpgcheck: no
 # yum_repository:
  #  name: epel
   
# description: EPEL YUM repo
 #   file: external_repos
  #  baseurl: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
   # gpgcheck: no
  
 
- name: install base tools and packages
  yum:
      name:
        - python-pip
        - gcc
      state: latest


